on:
  push:
    branches:
      - master

name: Create Slate Documentation on Push
jobs:
  test-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build documentation
      uses: ./
      env:
        DOC_BASE_FOLDER: .
        ZIP_BUILD: false
    - name: Deploy to GitHub Pages
      uses: maxheld83/ghpages@v0.3.0
      env:
        GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        BUILD_DIR: test-documentation/build/
